### ISSUE TITLE
Random Lag with Movements

### ISSUE THREAD

**Issue by EtornaZ** [SecondFaceSoftware/PortalRevolution-Issues#1]
I'm experiencing random lag with my movements. It's roughly a second of latency, as well as random speedups and slowdowns in my movements. My FPS doesn't seem to be connected as it happens whether I get 15 FPS or 60 FPS. My VSync is disabled. I restarted my PC but that doesn't fix the issue.

 OS: Windows 10 Pro
 GPU: NVIDIA Quadro K2000M
 CPU: Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
 RAM: 20.0 GB

If there's any other information you need from me, please let me know. Thank you.

**Comment by JJL772** [comment]
What is `m_rawinput` set to? `m_rawinput 2` enables some interpolation to improve input behavior at low frame-rates, maybe try that setting?

**Comment by EtornaZ** [comment]
It was automatically set to 2. I tried 1 and 0, but it didn't seem to affect anything.

**Comment by StefanH-AT** [comment]
Your GPU seems to be below min spec and on my lowest end system I can't reproduce this. I don't think there's anything I can do about this
