### ISSUE TITLE
Softlock in the spire

### ISSUE THREAD

**Issue by PortalWalker** [SecondFaceSoftware/PortalRevolution-Issues#10]
**Describe the bug**
You can get soft locked in the spire area

**To Reproduce**
1. After opening the door to the spire shoot a portal under the stairs in front of you
2. Shoot another portal to your left at the base of the stairs and enter it
3. If you drop down onto the shaft cover you can't get out without reloading

**Expected behavior**
Either remove the portal surface below the stairs or make the walls inside the hatch portalable

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: AMD RX 6650 xt
 - CPU name: AMD Ryzen 7 5800x3D
 - RAM (Quantity + Spec): 32GB 3800MHz CL 20

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/85197913/9703f05b-10da-493c-9e3c-8a0d0c91c615

**Comment by PortalWalker** [comment]
Alternatively you can also just walk around the guard rail on the right, so you don't even need to use the portal gun

**Comment by Mystical-Ace** [comment]
This was fixed in Release 1.0.3, looks like this issue was forgotten about
