### ISSUE TITLE
Trapped between vactubes in final chamber in sp_a2_playground, trapped behind glass in exit hallway in sp_a3_vactube_lumber

### ISSUE THREAD

**Issue by CLPSAW** [SecondFaceSoftware/PortalRevolution-Issues#103]
Hello, this is my first bug report, I would really like to contribute, considering Portal Revolutions is such a great mod.
I'll start with the two softlocks I experienced.

Steps to reproduce:
The first softlock is in the second part of chamber 4-9, I haven't memorized the names because the chapters are weirdly laid out (will comment on this at a later moment)
I went to the left side and jumped across the two vac tubes there, found a strange vent in the corner that I sadly couldn't open, and when I tried to go back, I got stuck forever in between the vac tubes.

The other softlock is in the room where you can get the "Two times the charm" achievement (Chamber 6-2) you can explore the rooftops and fall down behind the glass corridor. Now I would like to also make a suggestion here, just make it so that at least one window is broken instead of using invisible walls to prevent players from reaching this area.

Screenshots:
![Captura de Tela (3259)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/0a52e331-ad24-4163-9ed4-0dbee9c70fb3)
![Captura de Tela (3273)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/1a7b772e-e308-4642-beb0-44442f23b627)

 - OS: Windows 10
 - CPU/GPU: Intel HD Graphics 620
 - RAM (Quantity + Spec): 4gb

**Comment by Mystical-Ace** [comment]
First issue has been fixed, second issue has not been fixed

**Comment by Mystical-Ace** [comment]
Second issue was fixed a bajillion years ago, just forgot to close this issue
