### ISSUE TITLE
5 Bug Reports

### ISSUE THREAD

**Issue by CLPSAW** [SecondFaceSoftware/PortalRevolution-Issues#104]
It's me again, I decided to make a compilation report now instead of doing it one by one, so I'll be using a different format here, since there's no need to specify step by step how to reproduce, just check how the screenshots are numbered after the described issue below, I hope it's ok that I did it this way.

1. In Chapter 6, Chamber 7, the laser grid can't be seen through the opposite portal than the one placed behind the laser.
2. Reflection cube falls through the floor when dropped after quick-loading (rare, may never happen again)
3. Visual bug with this broken vent not being rendered through portal. Don't remember where this was, sorry. This could be related to lower shader detail settings, if so, disregard this because I did use a lower setting at some point to prevent input lag.
4. Another softlock. In Chamber 6-6 while trying "the fun solution achievement", I used the white gel to perform terminal velocity and then shot a portal on the white-painted floow near the angled panel to fling myself up to the catwalk, but I ended up at the very top of the chamber, landing on a catwalk, which would've been a perfect place for a secret, may I add, but it ended up being a softlock as I couldn't go back down.
5. In Chapter 8, there are Z-fighting going on all over the moving floors that cover the incinerator.

**Screenshots**
1.
![Captura de Tela (3283)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/14b30c09-c185-4f94-84b1-4e6046b0362e)
2.
![Captura de Tela (3285)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/7a0003d3-cd6a-4811-b45f-cfe34627edb9)
![Captura de Tela (3286)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/262a41fe-e4d8-4954-8710-0ae0b276c0f5)
![Captura de Tela (3284)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/bc48e7ef-ad4d-4541-9863-c4175d84d143)
3.
![Captura de Tela (3289)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/b035db1c-2b2b-4aa6-a775-b0c6b55ca8c7)
![Captura de Tela (3290)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/27482841-2433-495f-baaa-ea9a8580054d)
4.
![Captura de Tela (3282)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/b332a7a0-8974-41b4-b9d3-cfe59d571137)
5.
![Captura de Tela (3291)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/9f38ec3a-ab26-4deb-8d54-4f3c6593ae4e)

- OS: Windows 10
- CPU/GPU: Intel HD Graphics 620
- RAM (Quantity + Spec): 4gb

**Comment by Mystical-Ace** [comment]
It would be better if you made them separate issues, rather than combining them, since its easier to track and mark each as fixed

**Comment by StefanH-AT** [comment]
As ace said make individual issues for these
