### ISSUE TITLE
Chamber 6-6

### ISSUE THREAD

**Issue by pep0w** [SecondFaceSoftware/PortalRevolution-Issues#107]
I don't think this is how we are meant to do this. Took me around 15-20 minutes to do this. 
I was able to smear the white gel everywhere and just portal up to the door. Still got the "Boring Way" achievement though. 

You give me a way to paint, I'm gonna paint everything :D

https://i.imgur.com/du0QAol.png

![asd](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/7927176/2aae328d-79c2-4e72-bd45-03af1de893c8)

**Comment by Mystical-Ace** [comment]
That's the biggest issue with Conversion Gel. But given the time it took you to do it, and that you still got "The Boring Way" achievement (which can only be obtained if you solve the chamber in any way but the intended way), this won't be fixed.
