### ISSUE TITLE
Cubes do not stop playing airborne audio

### ISSUE THREAD

**Issue by gabe1cragger** [SecondFaceSoftware/PortalRevolution-Issues#108]
When airborne (i.e. by flinging), cubes play music. This is (I believe) expected. However, once they have been caught or touch the ground, the audio continues playing.

1. Go to a test chamber where cubes must be flung (I'm in 06, I think)
2. Fling a cube
3. Catch the cube, or allow it to land

Expected behavior is for the audio to end, I think.

Operating System - Windows 11
Processor - AMD Ryzen 5 5600H with Radeon Graphics
Installed RAM	- 16.0 GB (15.4 GB usable)

**Comment by PortalWalker** [comment]
https://www.youtube.com/live/ih3uMnGA0XI?si=oMNCKu6V8PTAiqZ8&t=4864
According to the developers, it is intentional

**Comment by gabe1cragger** [comment]
> https://www.youtube.com/live/ih3uMnGA0XI?si=oMNCKu6V8PTAiqZ8&t=4864 According to the developers, it is intentional

oh alright!
