### ISSUE TITLE
Trapped behind projector in sp_a1_final_test & sneak back through the closing vert door in sp_a1_bts_wind_2

### ISSUE THREAD

**Issue by CLPSAW** [SecondFaceSoftware/PortalRevolution-Issues#110]
1. Softlock behind the screen that says "no signal"
2. In chapter 2, you can softlock yourself if you enter the vertical door at the end of the conveyor belt and quickly walk back out of it, the dialogue will play as if you were in the next room. Will leave a video for this one.

1
![Captura de Tela (3438)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/0a1032fb-f1f2-4439-90ee-f543b19aa007)
![Captura de Tela (3439)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/5f9d5cfb-8bc1-46bc-8e46-2f2905d6a50e)
2
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/116120236/cb9b1f61-0427-495e-8dba-26ca2559168e

 - OS: Windows 10
 - CPU/GPU: Intel HD Graphics 620
 - RAM (Quantity + Spec): 4gb

**Comment by Mystical-Ace** [comment]
Next time, give your issue a more descriptive title (other than just "2 more softlocks"), and ideally, make two separate issues for the bugs, rather than lumping them together in one
