### ISSUE TITLE
Out of bounds area in ceiling in sp_a4_schrodinger_final

### ISSUE THREAD

**Issue by Original-Blank** [SecondFaceSoftware/PortalRevolution-Issues#113]
**Describe the bug**
Out of bounds area in *sp_a4_schrodinger_final*

**To Reproduce**
1. Place gel on the button platform and the floor below
2. Jump onto the side wall
3. Jump off onto the gel below and land on the opposite side in the ceiling

**Expected behavior**
Should be stopped from being able to get into the ceiling

**Screenshots**
![01](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/24685304/3c051432-3a34-4902-a0ae-1ce55d59c3e6)
![02](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/24685304/0e478eda-f4e6-40cc-8cae-d28d7398f964)
![03](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/24685304/14a05678-148a-477a-933b-ba2bd12b7882)
![04](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/24685304/887b7bad-9d92-460b-935e-a0b8895ca990)
![05](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/24685304/6487a17d-196f-4f91-a45f-b9efbb47d2f1)

**Video**
https://youtu.be/10AWWXeKRcM

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - GPU name: NVIDIA GeForce RTX 3060
 - CPU name: AMD Ryzen 7 5800X
 - RAM (Quantity + Spec): 32GB DDR4

**Comment by Mystical-Ace** [comment]
This doesn't break the puzzle in any way, so all I've done is patched the visible nodraw up there. Enjoy your little hidey spot.
