### ISSUE TITLE
 Cube that can be dragged into the elevator and after loading it will disappear

### ISSUE THREAD

**Issue by VovaShip47** [SecondFaceSoftware/PortalRevolution-Issues#117]
Steps to reproduce the behavior: map `sp_a3_climp`
We do this⬇

![20240113104050_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156499891/aaa76da4-9add-41dc-a77f-f42582d24092)
then we pick up the cube and carry it with us

![20240113104115_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156499891/21759582-d257-4539-82d8-df4893783bc7)

We carry the cube to the elevator

![20240113104125_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156499891/5eafd2e2-f3c7-4a90-9235-b13c19415572)
and we put the cube in the elevator

![20240113104134_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156499891/36bd5010-23ab-41ce-bdcc-a69e96575d52)
And now we go into the elevator ourselves

![20240113104149_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156499891/28a4230b-e242-4f93-a850-a3a699b90cd2)
after loading, the cube disappears

![20240113104201_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156499891/e0ece96a-805d-4713-966c-cbf9764572c1) (Do not pay attention to the Russian test in the save corner, I have Russian installed, thank you for understanding)

The conclusion should
be put at the end of the test
Material Emancipation Grill

**Comment by Scipply** [comment]
this is not an issue, the game just changes the map instead of making a transition. The only thing that should be done is putting a fizzler near the elevator or ignorin it

**Comment by Mystical-Ace** [comment]
This will not be fixed
