### ISSUE TITLE
Date displaying incorrectly on load screen

### ISSUE THREAD

**Issue by Sp33dwagen** [SecondFaceSoftware/PortalRevolution-Issues#119]
When the load screen is accessed a date may appear with the incorrect suffix.

**To Reproduce**
1. Go to '"load game" on a date that requires "th" suffix'
2. See error "13rd" displayed as opposed "13th"

**Expected behavior**
proper suffix for date.

**Screenshots**
![20240113045347_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156513656/6e923b2d-d9f3-4733-9749-59e784fccceb)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - GPU name: GeForce RTX 4080FE
 - CPU name: Intel Core i9-12900KS
 - RAM (32.0 GB + DDR5-6000 CL36-36-36-96)):

**Comment by StefanH-AT** [comment]
Thanks for letting us know. This will be fixed in 1.1.0
