### ISSUE TITLE
Game does not show all audio output devices in audio settings

### ISSUE THREAD

**Issue by memmam** [SecondFaceSoftware/PortalRevolution-Issues#12]
**Describe the bug**
Game does not show all audio output devices in audio settings. Game correctly used my default audio device when I started it, but the default audio device isn't listed, and so I changed it and can't change back, now I'm stuck with no audio.

**To Reproduce**
1. Have more than eight audio output devices
2. Go to 'Options'
2. Click on 'Audio'
3. Open 'Output Device' dropdown
4. Only eight output devices are shown

**Expected behavior**
All audio output devices should be shown

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/9062595/8f507609-e2be-4f08-ac45-23222de044a5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: Nvidia RTX 4090
 - CPU name: Ryzen 9 7950X
 - RAM (Quantity + Spec): 64GB DDR5-6000

**Comment by Freex-e** [comment]
@memmam I fixed this manually by editing some client files. To replicate my steps go to:

1. Portal Revolution\revolution\panorama\layout\pages\main-menu\settings-audio.xml
2. Edit and go to line 64 (as of the date of this comment)
3. Copy `<Label text="XXXXXX 8" id="audiodeviceconfig8"/>`
4. Paste and change the numbers to be 9, 10, ... until you have enough audio devices.
For some reason VSCode couldn't save the file so I just used notepad.

Works fine for me so far.
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/124922304/ee08010e-37b3-4599-8320-37f0741e9603)

**Comment by StefanH-AT** [comment]
Thanks for reporting. Never seen anyone with this many audio devices. Most impressive! I'll extend that list to show more devices

**Comment by memmam** [comment]
@StefanH-AT the life of a livestreamer: lots of audio devices. Thanks for the fix! <3

**Comment by memmam** [comment]
@StefanH-AT just want to confirm what you changed the limit to? At current count I have 18 sound devices (theoretically up to 20 if I enabled the last two sound devices in Elgato Wave Link), and my setup is particularly intense - I think a limit somewhere around 25 should be reasonable for 99% of users.
