### ISSUE TITLE
You can complete Chamber 4 - 14 without turning off the power

### ISSUE THREAD

**Issue by A-Loot** [SecondFaceSoftware/PortalRevolution-Issues#121]
**Describe the bug**
I found an alternative way to get the cube in position

**To Reproduce**

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/105282948/12e3cdce-e53a-433c-b747-bd60ede298dd

**Expected behavior**
There should something to prevent the cube from reaching the top, like replacing some of the portal surface so that you can't place portals high enough to be able to do this.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - GPU name: 
 - CPU name: 
 - RAM (Quantity + Spec):

**Comment by StefanH-AT** [comment]
This will be fixed in 1.1.0
