### ISSUE TITLE
vulnerabilities of sp_a3_climb

### ISSUE THREAD

**Issue by NoX-programer** [SecondFaceSoftware/PortalRevolution-Issues#128]
**Describe the bug**
The map sp_a3_climb has vulnerabilities through which quirky players can get into places they shouldn't.

**To Reproduce**
[First violation](https://youtu.be/AiMCeDasbz8?t=481)... I think
[Breakthrough further](https://youtu.be/AiMCeDasbz8?t=906)
[And higher](https://youtu.be/AiMCeDasbz8?t=1061)
[Also, tricks beyond the allotted limits](https://youtu.be/AiMCeDasbz8?t=1978)
I'm not insist anyone to watch full [video](https://youtu.be/AiMCeDasbz8) - it turned out to be long. But if you need - you can.

**Desktop:**
 - OS: Win10
 - GPU name: NVIDIA GeForce GTX 1080
 - CPU name: Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz
 - RAM (Quantity + Spec): 32G

**Comment by StefanH-AT** [comment]
Thanks for reporting but since these tricks don't really affect the casual experience, as you need to go out of your way to do this, I don't think it's necessary too address this. I am adding some more textures to places up above though
