### ISSUE TITLE
Kelvin has NO degrees

### ISSUE THREAD

**Issue by Cassetete** [SecondFaceSoftware/PortalRevolution-Issues#132]
**Describe the bug**
A dialog said "4000 degrees Kelvin"

**Expected behavior**
Dialog must says "4000 Kelvin"

**Comment by Ryltarr** [comment]
This is a direct reference to the original Portal where GLaDOS says:
> All Aperture technologies remain safely operational up to 4000 degrees kelvin. Rest assured, that there is absolutely no chance of a dangerous equipment malfunction prior to your victory candescence. Thank you for participating in that Aperture Science Enrichment activity. Goodbye!

So, while it is incorrect, it isn't really a bug.

**Comment by Mystical-Ace** [comment]
Ryltarr is correct, this is not a bug
