### ISSUE TITLE
Level 4-10 unsolvable

### ISSUE THREAD

**Issue by gabygg4** [SecondFaceSoftware/PortalRevolution-Issues#14]
When trying to solve puzzle 4-10 the ball won't bounce to the other side and keeps hitting the wall.
Map: sp_a2_tbeam_flings

It looks like the ball loses speed when going through the portal.

[Video of the bug](https://youtu.be/aFrVyCLIaho)

 - OS: Windows 11 Pro 22H2 22621.2861
 - GPU name: Saphire nitro radeon 7900XTX
 - CPU name: Core i7-13700K
 - RAM: 32GB (2x16GB) DDR5-5600

**Comment by ArcherTheReal** [comment]
You can still solve it by going up there first and then grabbing the sphere

**Comment by Mystical-Ace** [comment]
This should be fixed in Release 1.0.5
