### ISSUE TITLE
Lost all settings, went to 640 x 480 resolution

### ISSUE THREAD

**Issue by Organic-Marble** [SecondFaceSoftware/PortalRevolution-Issues#140]
**Describe the bug**
I've been playing for a week or so and finished the game. Was on 2nd playthrough. When I started the game this morning all my video settings were gone; it came up in 640 x 480 resolution and all the settings I had modified to stop the game crashing were gone.
**To Reproduce**
Start the game

**Expected behavior**
I expected all the settings I had tweaked over the last week to be at the same values

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - GPU name: GTX 1040 Ti
 - CPU name:  intel i5-4440S
 - RAM (Quantity + Spec): 16 G

**Comment by PortalWalker** [comment]
Same thing happened to me. Probably caused by last update
