### ISSUE TITLE
Patch 1.0.6 causes game to default to 4k/fullscreen (which is not supported by my hardware).

### ISSUE THREAD

**Issue by danbrakeley** [SecondFaceSoftware/PortalRevolution-Issues#141]
**Describe the bug**
The game appears to start at 4k, which results in the "Strata" boot logo animation to be larger than my display area, after that it resizes everything, and sometimes the game starts, and sometimes it minimizes and trying to click the task bar icon to restore it just causes the game to minimize again.

**To Reproduce**
1. Get release 1.0.6 in Steam, click Play
2. See "Strata" boot logo animation show up larger than the visible area on the primary monitor, and spilling over into second monitor.
3. Wait for boot logo animation to complete, and game to drop you back on your desktop with the game minimized.

**Expected behavior**
Game boots into a resolution that is supported by my hardware.

**Notes**
Fixed by editing video settings in `steamapps\common\Portal Revolution\revolution\cfg\video.txt`.

**Hardware:**
 - OS: Windows 10 Pro (all Windows Updates as of 2024-01-16)
 - GPU name: NVIDIA GeForce RTX 2070 w/ studio driver v546.01
 - CPU name: AMD Ryzen Threadripper 3960X
 - RAM (Quantity + Spec): 128GB DDR4-3200 (1600MHz, CL22, ECC)

**Comment by danbrakeley** [comment]
OK, I just tried it again to make sure I had the description correct, and this time I got to a usable main menu! I went in the settings, and it said it was running at 4k fullscreen (my monitor is 2560x1440, so I don't know if my monitor was downscaling, or the UI was lying). I changed it to 2560x1440 windowed fullscreen, and then quit and restarted it, and everything seems OK now!

**Comment by danbrakeley** [comment]
OK, in `steamapps\common\Portal Revolution\revolution\cfg\`, I can see that `videodefaults.txt` was updated yesterday (when I got the 1.0.6 patch), and it is set to 3840x2160, fullscreen 1, nowindowborder 0. The `video.txt` was updated today, and is set to 2560x1440, fullscreen 0, nowindowborder 1.

I tried deleting `video.txt`, and the issue reproduced. Did previous patches not use video.txt? Or did it get overwritten or deleted by the 1.0.6 patch? And I think defaulting to 4k is a mistake.

**Comment by danbrakeley** [comment]
For anyone else with this issue, looks like you can edit `steamapps\common\Portal Revolution\revolution\cfg\video.txt`. Mine currently looks like this:
```
"VideoConfig"
{
	"setauto.cpu_level"		"0"
	"setauto.gpu_level"		"3"
	"setauto.mat_antialias"		"8"
	"setauto.mat_aaquality"		"0"
	"setauto.mat_forceaniso"		"1"
	"setting.mat_vsync"		"0"
	"setting.mat_triplebuffered"		"0"
	"setting.mat_grain_scale_override"		"-1.0"
	"setauto.gpu_mem_level"		"2"
	"setting.mem_level"		"2"
	"setting.mat_queue_mode"		"-1"
	"setauto.csm_quality_level"		"3"
	"setting.mat_software_aa_strength"		"0"
	"setting.mat_motion_blur_enabled"		"0"
	"setting.mat_dynamic_tonemapping"		"1"
	"setting.mat_disable_bloom"		"0"
	"setting.mat_colorcorrection"		"1"
	"setting.mat_texturestreaming"		"0"
	"setting.defaultres"		"2560"
	"setting.defaultresheight"		"1440"
	"setting.refresh"		"165"
	"setting.aspectratiomode"		"0"
	"setting.fullscreen"		"0"
	"setting.nowindowborder"		"1"
}

```

**Comment by ozxybox** [comment]
If you delete both `video.txt` and `videodefaults.txt`, the engine will choose defaults according to your hardware.

**Comment by danbrakeley** [comment]
Good to know!

Also, additional info: running Steam's "Verify integrity of game files" will recreate both `videodefaults.txt` and `video.txt`, and if you have a custom `video.txt`, that will be destroyed, and the file contents will be replaced with the same 4k/fullscreen settings that `videodefaults.txt` contains.

![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/6772870/22f33d44-74bb-4021-8669-ce80140b2f95)
