### ISSUE TITLE
Can't Install Game On Linux Mint (Ubuntu 22) OS - "missing shared content"

### ISSUE THREAD

**Issue by drobin04** [SecondFaceSoftware/PortalRevolution-Issues#147]
When trying to install the game, Steam gives me an error, 'missing shared content'. 

**To Reproduce**
1. Open store/library page for game
2. Click 'Install'
3. See error

**Expected behavior**
Game downloads and installs

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/90974129/464ec7d3-d918-48f5-8dfc-72d8c4a2a2dd)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 (based on Ubuntu 22)
 - GPU name: Nvidia 1060 3GB
 - CPU name: Ryzen 7 2700
 - RAM (Quantity + Spec): 16GB

**Comment by Sergo3682** [comment]
For me Proton Hotfix works perfectly. Try it.

**Comment by Mystical-Ace** [comment]
Do you own Portal 2 on Steam?
