### ISSUE TITLE
Cube falls between portal and open space

### ISSUE THREAD

**Issue by Jomiph** [SecondFaceSoftware/PortalRevolution-Issues#148]
**Describe the bug**
In The Surface, when you reach the first big,multi level test area,  I tried bringing the cube with me through the orange portal at the bottom. The cube clipped and gor stuck under ground.

**To Reproduce**
1. Go to mentioned test area
2. Grab cube
3. Jump through orange portal
4. Now you're thinking with portals

**Expected behavior**
Cave Johnson coming back to life with Walt Disney

**Screenshots**
https://steamcommunity.com/id/papa_sloth/screenshot/2296339979076025211/

Hope this helps.

**Comment by Mystical-Ace** [comment]
This is already fixed, just not updated
