### ISSUE TITLE
Laser doesn't kill the player

### ISSUE THREAD

**Issue by Sergo3682** [SecondFaceSoftware/PortalRevolution-Issues#149]
If you walk into the laser beam, it doesn't deal you any damage.

**To Reproduce**
1. Just walk into laser beam.
2. See error

**Expected behavior**
The laser must damage the player and kill him.

**Screenshots**
![bug](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/97442751/10f3dd81-1812-4c18-b0da-0e73880328f4)

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.5
 - GPU name: Intel UHD Graphics 620 
 - CPU name: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - RAM (Quantity + Spec): 8gb DDR4 2400 MHz

**Comment by PortalWalker** [comment]
This is intentional, as it is in other Portal 2 mods because the laser doing damage doesn't have any purpose

**Comment by Mystical-Ace** [comment]
This is intentional and not a bug.
