### ISSUE TITLE
"back to bed" achievement not unlocking on game completion 

### ISSUE THREAD

**Issue by eightheve** [SecondFaceSoftware/PortalRevolution-Issues#151]
After finishing the game, the achievement isn't granted. Not even after restarting the final episode several times, and then even starting from the episode previous.

 - OS: Windows 10
 - GPU name: NVIDIA GeForce GTX 1080
 - CPU name: AMD Ryzen 5 2600X Six-Core
 - RAM (Quantity + Spec): 16gb 2400Mhz ddr4

**Comment by tobybug** [comment]
Not the dev, but I will note that I didn't get the achievement myself until finishing the credits and watching the end credits scene (which I recommend, it caps off the story a little better than the scene just before the credits). You may need to do so to get the achievement to work.

**Comment by ZacTheHac** [comment]
> Not the dev, but I will note that I didn't get the achievement myself until finishing the credits and watching the end credits scene (which I recommend, it caps off the story a little better than the scene just before the credits). You may need to do so to get the achievement to work.

thank you very much for this mention of an ending scene. I was utterly confused. The game auto-paused for me TWICE when the credits ended, and I assumed that was the game being over, with a black background because you're just dead or something.
This time I noticed it said "resume" instead of "new game".
Watching the ending scene got the achievement.

**Comment by Wedge009** [comment]
I'm not sure what happened to me, whether I did something silly accidentally press escape or some such, but the first time I finished the credits I think I got sent straight to the main menu. It was only when I reloaded the completion save, went through the credits all over again, that's when I got the ending scene, which then gave me the completion achievement. Weird.
