### ISSUE TITLE
Walking is like walking on ice

### ISSUE THREAD

**Issue by thany** [SecondFaceSoftware/PortalRevolution-Issues#153]
**Describe the bug**
Walking is like walking on ice. When walking in any direction, and then releasing the corresponding walk key (regardless of input device) the character keeps walking in the same direction for about a quarter second extra.

It's just like those awful scroll animations where software insists that everything that ought to be instant, must smoothly and slowly transition from one state (walking) to another (standing still).

It's triggering my motion sensitivity, and that means nauscia. All other FPS that I play do not have this problem. 

**To Reproduce**
1. Start game
2. Press walk key
3. Release walk key
4. Observe how you don't actually stop walking the moment you release the key

**Expected behavior**
Release walk key = stop walking
And no nauscia.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: RTX2080
 - CPU name: Ryzen 9 7900
 - RAM (Quantity + Spec): 32GB DDR5 7200MT/s

**Comment by StefanH-AT** [comment]
I can't reproduce this
