### ISSUE TITLE
Crosshair too thin

### ISSUE THREAD

**Issue by thany** [SecondFaceSoftware/PortalRevolution-Issues#154]
**Describe the bug**
 Crosshair is too thin for me. I play on 4K on a 27" monitor, and it seems the crosshair is hardcoded to be 1 physical pixel thick, rather than scaling properly with the UI. 

**To Reproduce**
1. Play the game on a HDPI 4K screen.

**Expected behavior**
Crosshair is more-or-less the same thickness (in millimetres) regardless of resolution or DPI.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: RTX2080
 - CPU name: Ryzen 9 7900
 - RAM (Quantity + Spec): 32GB DDR5 7200MT/s

**Comment by Mystical-Ace** [comment]
I plan on a 4k screen as well, and I don't have any issues with the crosshair? There's an option in the settings to scale the crosshair

**Comment by thany** [comment]
Well good for you I guess, but the scaling option doesn't really do anything for me. The five little dots remain to be 5 little dots. Not sure what it does for you, so maybe it sort of differs by system settings or something.

**Comment by StefanH-AT** [comment]
This'll be fixed in 1.4.0
