### ISSUE TITLE
"Unsupported graphics card" warning paired with broken savegame

### ISSUE THREAD

**Issue by extremMiSt** [SecondFaceSoftware/PortalRevolution-Issues#156]
**Describe the bug**
after having played the game for a bit, I got hit by #140. but after a relaunch I also got hit with 
![grafik](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/1934286/15acfd9e-fdc5-4775-aa1c-1724e00d9f0a)

I can click this away just fine and the menu loads up, but when trying to load the savegame I played before relaunch then it gets to 94% "Retrieving game data" and then crashes after about a minute. this only happens with a few savestates and does not happen on a new game.

**To Reproduce**
1. Start the game 
2. Click away the "Unsupported graphics card" (see screenshot above)
3. Click "save/load game" 
4. Select one of the broken savegames
5. the game closes after about a minute

**Expected behavior**
the game should have loaded

**Screenshots**
not really applicable, but ask if you know what you're looking for.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 "virginia"
 - GPU name: GeForce GTX 1050 Ti, using nvidia-driver-535.146.02
 - CPU name: AMD A8-7600 Radeon R7
 - RAM (Quantity + Spec): 2x8gb ddr3

I am aware that this might be two unrelated bugs (graphics card + savefile corruption), but both symptopms occured after the update to Patch 1.0.6

**Comment by extremMiSt** [comment]
small clarification:
I went through most of the savegames now and the only one affected seems to be the one I played after resetting my grapgics settings and relaunching.

**Comment by extremMiSt** [comment]
the latest hotfix 2 fixed the unsupported graphics for me, which is interesting cause I am on an nvidia card. but fixed is fixed :)
that leaves the weird corrupted savegame

**Comment by Mystical-Ace** [comment]
> the latest hotfix 2 fixed the unsupported graphics for me, which is interesting cause I am on an nvidia card. but fixed is fixed :) that leaves the weird corrupted savegame

Try loading an older save. Sometimes saves get corrupted when the game updates
