### ISSUE TITLE
I broke the suction pipe?

### ISSUE THREAD

**Issue by boop5** [SecondFaceSoftware/PortalRevolution-Issues#157]
**Describe the bug**
In the first level of "The Climb" you come through a door and there is a suction pipe in the middle of the room. I managed to disable it and now I can't continue the level

**To Reproduce**
1. actually use the suction pipe, advanced through the door to the next room
2. there is a room you apparently aren't supposed to go into, but you can shoot a portal through the door to get inside
3. jump over the fence (going down the stairs) to setup a second portal
4. well. it seems to be over now. you can't go back. so I reloaded the last checkpoint and now the suction pipe is dead. even after a game restart

**Expected behavior**
The suction pipe still works after finishing the room

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/4655466/e2b83969-06d4-4d9e-a4d4-a750d44c95f6)

**Comment by boop5** [comment]
This is the room I'm talking about

![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/4655466/ba22e0ea-6025-44b0-a1cb-afc777fd0a20)

**Comment by Mystical-Ace** [comment]
How did you get into the chamber from the observation room? Unless you think it's a reason for it?

Just tried doing this myself and it still worked, at most I've seen the particles disappear for some people, but the suction itself should still work regardless

**Comment by boop5** [comment]
oof. okay, maybe it was just the particles. I don't think I even tested it. My bad.
