### ISSUE TITLE
sp_a3_labs Softlock | Human core disappears when putting it in the dock to fast

### ISSUE THREAD

**Issue by nenderson** [SecondFaceSoftware/PortalRevolution-Issues#164]
**Describe the bug**
Human core disappears when putting it in the dock to fast

**To Reproduce**
1. Go to map sp_a3_labs
2. Go pick up the human core
3. Go back to where the dock for the core should be 
4. Look out the window for a second the continue the dialoge
5. Hold the core over the dock that does not display

> And poof core gone, softlocked

**Expected behavior**
The core shouldnt disappear

**Video**
https://medal.tv/de/games/portal-revolution/clips/1QBYNk4t2EnqAi/O1fJxlvE9PJd?invite=cr-MSxHWU4sMjEwNjIxNDg0LA?mobilebypass=true

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU name: NVIDEA GeForce RTX 3070 Ti (ASUS TUF GAMING OC)
 - CPU name: AMD Ryzen 9 5900x
 - RAM (Quantity + Spec): 2*16GB 2133 MHz (Rated for 3200MHz)

**Comment by nenderson** [comment]
Windows 11 btw

**Comment by Mystical-Ace** [comment]
Duplicate of #2
