### ISSUE TITLE
Portal gun vanishes from hands during the pipe trip in chamber 6-8

### ISSUE THREAD

**Issue by DavidResin** [SecondFaceSoftware/PortalRevolution-Issues#165]
**Describe the bug**
In chapter 6, chamber 8, there is a pipe trip. When going into the pipe, the portal gun momentarily vanishes from the player's hands, which is unfortunate and breaks immersion.

**To Reproduce**
1. Go to champter 6, chamber 8
2. Enter the pipe
3. The portal gun vanishes then reappears upon exiting

**Expected behavior**
The portal gun should remain visible during the whole time.

**Screenshots**
![Before](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/17401752/15b8fb75-42ed-4007-b4e1-d21b31739237)
![During](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/17401752/9fc857bd-feaf-4dda-ac97-5f16df454b46)
![After](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/17401752/f0b0988d-f43e-4f25-88f7-9e489d9b4386)

**Desktop (please complete the following information):**
- OS: Windows 11
- GPU name: Nvidia RTX 3090
- CPU name: Intel Core i9-13900K
- RAM (Quantity + Spec): Corsair Vengeance 2 x 16GB, 6000 MHz, DDR5 RAM

**Comment by DavidResin** [comment]
This also happens in room 7-7.

**Comment by Mystical-Ace** [comment]
This is not a bug, its intentional with the way we do vactube rides.
