### ISSUE TITLE
sp_a1_cube_fling_intro Cannot put portal onto white wall

### ISSUE THREAD

**Issue by Gold1Gold** [SecondFaceSoftware/PortalRevolution-Issues#166]
I am unable to put a portal onto the white wall in sp_a1_cube_fling_intro. The wall is for when you need to fling the cube to yourself so you can reach it.

Leaving to main menu and loading the save again fixes the issue, though I believe I should still submit this.

**To Reproduce**
1. Go to the room
2. Shoot the wall
3. Wall doesn't accept a portal

**Expected behavior**
I believe that the wall should be able to accept a portal as I see videos of people able to do so.

**Screenshots**
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/79869720/3e905f90-39bc-4d18-a9f9-8700c4c87700
(I believe a video shows it better, a screenshot of the wall is attached too though)
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/79869720/9f4ac10f-3262-4da7-a3f6-ecb780d22e74)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Ver. 23H2)
 - GPU name: RTX 3080 12GB VRAM (Brand: Gigabyte)
 - CPU name: AMD Ryzen 7 5800X
 - RAM (Quantity + Spec): 32GB DDR4 2133MHz

**Comment by StefanH-AT** [comment]
This is intentional to prevent players from sprinting past the fizzler. Not elegant but was necessary to mitigate this unintended solution
