### ISSUE TITLE
Out of bounds area on sp_a1_bts_wind

### ISSUE THREAD

**Issue by MidniteTheProtogen** [SecondFaceSoftware/PortalRevolution-Issues#17]
**Describe the bug**
You can get out of bounds on sp_a1_bts_wind in this spot

**To Reproduce**
1. Go to the end of the conveyer belt
2. Grab some cubes before they fall off into the pit
3. Make a cube tower against the sloped wall
4. Use the cube tower to jump on top of the sloped wall
5. Walk forwards and drop down into the out of bounds area

**Expected behavior**
Should be stopped by an invisible wall

**Screenshots**
![20240106201717_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/d4345452-ad74-4e7f-8056-77d29749ae1a)
![20240106201838_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/cadc03ad-d57a-4769-9d57-5037883e3c87)
![20240106201856_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/d09f516f-7106-4fc9-9d0e-4c85bb8f061a)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit 21H2
 - GPU name: NVIDIA GeForce GTX 1660 Ti
 - CPU name: AMD Ryzen 5 3600X
 - RAM (Quantity + Spec): 16GB (2x8gb) 1600MHz

**Comment by StefanH-AT** [comment]
You are not out of bounds
