### ISSUE TITLE
The Climb puzzle broken after loading a saved game

### ISSUE THREAD

**Issue by millerti** [SecondFaceSoftware/PortalRevolution-Issues#171]
**Describe the bug**
When loading a game in the puzzle below, there is a game-breaking problem with one of the game elements (or I just can't solve the puzzle lol).

**To Reproduce**
1. Load a save file in the screenshotted puzzle in the chapter The Climb
2. The Pneumatic Diversity Vents are not sucking anything into them, and I don't think any of the switches in the level turns them on.

**Expected behavior**
I believe these vents need to be on in order to solve the puzzle. No elements in the test chamber seem to activate them. And I believe they were working when I first played through into this chamber... they just don't work when I load the game.

**Screenshots**
![the climb](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/776667/e7871fcc-8fae-4c54-9faa-1ea5bfecb104)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: nVidia RTX 3080
 - CPU name: AMD 7800x3D
 - RAM (Quantity + Spec): 64GB 6000mhz DDR5

**Comment by Mystical-Ace** [comment]
The only thing broken here is the particle being gone. The suction tube will still suck things into it regardless
