### ISSUE TITLE
These columns on sp_a2_playground have no collision and can be walked through (see video).

### ISSUE THREAD

**Issue by TooMuchDog1** [SecondFaceSoftware/PortalRevolution-Issues#172]
**Describe the bug**
These columns on sp_a2_playground have no collision (see video).

**To Reproduce**
Load the map and walk into the columns.

**Expected behavior**
You shouldn't be able to walk through the columns.

**Screenshots**
See video: https://youtu.be/SIEXdg4tFis

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: RTX 3050ti
Processor	AMD Ryzen 9 6900HS with Radeon Graphics           3.30 GHz
Installed RAM	16.0 GB (15.2 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by StefanH-AT** [comment]
This will be fixed in 1.4.0
