### ISSUE TITLE
[Spoiler] Pressing the red button in the Climb in Control Room 4 while time is up can end in endless reloading loop

### ISSUE THREAD

**Issue by DocoDan** [SecondFaceSoftware/PortalRevolution-Issues#179]
**Describe the bug**
There is an overlap in the last control room of not succeeding in pressing the red button in Control room 4
in the climb just in time and succeeding to press the button which results in an endless reloading/ dying loop.

**To Reproduce**
1. Go to The last red button in Control Room 4 in the chapter in the climb
2. Click on the red button after killing the three robots just before time is up

4. You die while the NPC dialouge "You did it!" "Yes, you did it" endlessly reboots

**Expected behavior**
Either being killed or succeeding in finishing the level

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - GPU name: Geforce 1030 
 - CPU name: 
 - RAM (Quantity + Spec): 8

**Comment by Rubik95** [comment]
the same error happened to me. Press the red button seconds before you die.

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/47611100/9464f47e-88ed-49cc-a61f-6cf110965b40
