### ISSUE TITLE
Autosave can occur during 0 seconds left on control room puzzles

### ISSUE THREAD

**Issue by lewri** [SecondFaceSoftware/PortalRevolution-Issues#180]
**Describe the bug**
I have found that an autosave is able to trigger in the Control Rooms of the 5 minute timed puzzle in Chapter 8 at the point the time reaches 0. This can cause the game to go into a perpetual loop of loading the autosave and ending.

**To Reproduce**
1. Begin the timed puzzle in the spire
2. Press a control room pipe deactivation button at or near 0 seconds. An autosave triggers
3. Game ends and tries to reload from the autosave.

**Expected behavior**
Either for the autosave not to happen at that stage, roll back to the last stage.

**Screenshots**
![20240128131648_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/20030128/e01b38a6-d63d-4563-95a4-da427730d053)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: AMD Radeon RX 7600
 - CPU name: AMD Ryzen 5 3600
 - RAM (Quantity + Spec): 16GB DDR4

**Comment by Danloza** [comment]
I came here to second this bug. I pressed the 4th button and the audio kept looping between reload screens. 

To reproduce: 
Same steps as above. 

Expected behavior:
Timer stops when button is pressed or stage resets to previous autosave. 

Specs:
OS: Windows 10. 
GPU: Nvidia 3060ti
CPU: AMD Ryzen 7 5800X
Ram: 16 GB 2400 MHz.

**Comment by zethis** [comment]
Same here during the "The Remote Execution"
I start a [discussion](https://steamcommunity.com/app/601360/discussions/0/4211496988420463155/) in Steam, but don't take care of it, as i post here:

**Comment by jeff-hiner** [comment]
Just had the exact same thing happen.

**Comment by lewri** [comment]
> Same here during the "The Remote Execution" I start a [discussion](https://steamcommunity.com/app/601360/discussions/0/4211496988420463155/) in Steam, but don't take care of it, as i post here:

Just for visibility -- currently 4 additional 'me too' comments in your Steam discussion that should be counted here.

**Comment by jjones82** [comment]
Came here to make sure this was reported as well. I didn't pay attention to the actual timer, but I know I was running low on time and assume I clicked the button right as time ran out which caused the autosave to trigger, but not before the "end" was triggered. So it was causing an endless loop. 

Ended up having to go back to the last manual save, which unfortunately was the first entry to the teleportation chamber. Just a reminder on games you can manually save on... save often!

**Comment by Mystical-Ace** [comment]
Fixed
