### ISSUE TITLE
Weighted Storage Cube stuck :(

### ISSUE THREAD

**Issue by undeaDD** [SecondFaceSoftware/PortalRevolution-Issues#181]
**Describe the bug**
Cube Stuck and cannot be reset without reloading the whole level

**To Reproduce**
Let the cube fall through the hole ( happened by accident ) ?!

**Expected behavior**
Either add a reset Button or make the hole smaller ^^' idk

**Screenshots**
![Screenshot 2024-01-28 192149](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/8116188/049a3ee8-7ae1-463f-beb8-274e4b1d1d8d)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - GPU name: RTF 3080 Ti FE
 - CPU name: i9-12900K
 - RAM (Quantity + Spec): 32gb

**Comment by Mystical-Ace** [comment]
Already fixed
