### ISSUE TITLE
Multiple Glitches around the "secret" panel door of the aerial faith plate chamber

### ISSUE THREAD

**Issue by Brainwave018** [SecondFaceSoftware/PortalRevolution-Issues#182]
**Describe the bug**
A visual glitch that blurs and distorts what can be seen through a panel doorway, walking through pistons, and invisible platforms.

**To Reproduce**
Steps to reproduce the behaviour:
Go to Chapter 1, and then to the first Ariel faith plate(AFP) level.
after the AFP is recalibrated use them with portals to launch off the white wall on the right of the chamber. This will produce a ledge and a back door opens to let you back into the chamber. After exiting the door closes behind you. Then manually jump back over to the platform without portals, and walk back around to the doorway. You will then experience the glitch.

Also, the platforms that extend are invisible from the start of the chamber, so you can jump onto thin air.

**Expected behaviour**
I expected to see the environment clearly on the other side of the doorway. And not walk through pistons.

**Desktop:**
 - OS: Windows 10
 - GPU Name: GTX 1650S
 - CPU name: i7 - 11700F
 - RAM (Quantity + Spec): DDR4 16GB

**Screenshots**

Visual Glitch:

![20240131190419_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/faae857f-acf5-4721-9a9e-81d0684b7e6d)
![20240131190358_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/30dbbf46-eb22-40eb-9b3d-b6d43c9426c7)
 ![20240131190351_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/a420deea-4a0f-4fa1-8cf7-6f753776ab14)
![20240131190338_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/e13bbb14-df86-4385-afb3-8f2e58453d0e)
![20240131190343_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/071b1c6f-588a-411d-879b-b837b14ba0be)
![20240131190302_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/02e8514f-cfe1-4890-9ed1-9f9da5bf62a1)
![20240131190309_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/e0c03562-cd11-4f9d-b904-151c6631945a)
![20240131190326_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/fc001b0c-2c11-48e3-820f-a554f65d1fc4)
![20240131190331_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/2c8aad07-9a14-47e3-b87f-ceb6cfc9f62f)

Invisible Platform:

![20240131191052_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/00fa1ec5-0e4a-4522-8eae-f54a96f36c36)
![20240131191102_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/fcddcf85-a9b5-4963-8ea3-cb540908c0cd)

Piston clipping:

![20240131191501_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/8d3898a1-42df-4771-8fb0-81fbff8906f6)
![20240131191515_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158262698/f92a0e55-e9ff-4f7e-ad0a-70b594738b60)

**Comment by Mystical-Ace** [comment]
Most are already fixed. So I'll close this as completed for now. Next time, don't lump issues together, even if its in the same map. Creating separate issues for each bug or problem in a map is far easier for us to track.

**Comment by Brainwave018** [comment]
@Mystical-Ace That was a fast fix, I posted it as soon as I encountered it. If I find anything else I'll make separate posts. Thanks
