### ISSUE TITLE
4-10 problems with the bouncing physics of the ball

### ISSUE THREAD

**Issue by T4CTiC** [SecondFaceSoftware/PortalRevolution-Issues#185]
**Describe the bug**
When I play through the level, I have to bounce the ball over the water towards the button. When the ball bounces it takes weird jumps. And way lower then what I see on others video's. Only on ocation the ball barrely makes it onto the platform... but that way the achievement "Bullseye" doesn't work.

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158519379/53f016bd-6d96-4a88-881e-713a9f716cf9

**To Reproduce**
Play the map as normal.
portal at the platform below the ball"drop" then blue goo at the edge of the water, so the ball can bounce from the canted portal, on the goo, over the water, into the button (that's where the problem starts :)

**Expected behavior**
I expected the ball to just jump into the button. Now, the ball doesn't even make it till over the water. and not in  a straight line towards the goal.

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/158519379/90141e6f-35ad-4c70-8ac2-09291a4c4d35)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: NVIDIA GeForce RTX 3060 Ti
 - CPU name: Intel Core i5-9600K CPU @ 3.70GHz   3.70 GHz
 - RAM (Quantity + Spec): 16GB RAM

**Comment by Mystical-Ace** [comment]
This can't be fixed. We did our best but sometimes the game just breaks regardless. Try restarting the map or reloading a save, or just catch the ball and move on.
