### ISSUE TITLE
Stuck in elevator during "The Climb"

### ISSUE THREAD

**Issue by katzelad** [SecondFaceSoftware/PortalRevolution-Issues#187]
**Describe the bug**
I always get stuck inside the elevator at the end of the turned-out-not-to-be-a-test-chamber during "The Climb".

**Expected behavior**
The elevator should lead somewhere.

**Screenshots**
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/8028735/27fa6fff-37a4-472f-87a0-a493afb4a0df

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: 3060 Ti
 - CPU name: i7-7700
 - RAM (Quantity + Spec): 24gb DDR4

**Comment by StefanH-AT** [comment]
I can't seem to watch this video

**Comment by katzelad** [comment]
@StefanH-AT I am using Firefox and it plays well.
There is an elevator after finishing the big level where you have to spray white fluid on everything (in which the companion states at the end that it turned out not be a test chamber after all).
The elevator is going up for a bit and then simply stops, without any loading screen. The door does not open.

**Comment by StefanH-AT** [comment]
I think I found the issue. If you get to the top of the elevator before Conly is done talking, the transition won't trigger, since that map used an older level transition method. Should be fixed in the next update
