### ISSUE TITLE
sp_a3_labs softlock

### ISSUE THREAD

**Issue by Yinkahah** [SecondFaceSoftware/PortalRevolution-Issues#189]
just face to panel
its works if u do it before it finally opened
just look at it, and it sometimes works, depends on the angle of view, i think

https://youtu.be/tUzJiTeK69E

 - OS:  Windows 11 22H2
 - GPU name: radeon r9 270
 - CPU name: ryzen 5 4500
 - RAM (Quantity + Spec): 4*4 gb

**Comment by Yinkahah** [comment]
sometimes it also works after panel opens

**Comment by Mystical-Ace** [comment]
Already fixed
