### ISSUE TITLE
Props not dissolving in a fizzler.

### ISSUE THREAD

**Issue by nikolasle** [SecondFaceSoftware/PortalRevolution-Issues#190]
**Describe the bug**
Cube props in sp_a2_outside that fall from the edge don't get dissolved.

**To Reproduce**
1. Go to sp_a2_outside, at the part where you fling yourself
2. Step on the edges, cubes should fall
3. Finish the test normally, while bringing one of the cubes
4. Put it in the fizzler

**Expected behavior**
The cube should be dissolved

**Screenshots**
![20240203195556_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/59582789/5b0423a0-5682-45fb-a8bb-8a8f6000c995)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: NVIDIA GeForce GTX 1650
 - CPU name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
 - RAM (Quantity + Spec): 32677 Mb

**Comment by Mystical-Ace** [comment]
That's a piece of the test chamber, not a weight storage cube. Therefore, it wouldn't make sense for it to be dissolved.
