### ISSUE TITLE
map bug (door kill player and do 5 fps)

### ISSUE THREAD

**Issue by soloveu73** [SecondFaceSoftware/PortalRevolution-Issues#193]
### Game Version

Version 1.1.0

### Describe the bug

something is wrong in room 6 on the map "sp_a1_cube_fling_intro"

### To Reproduce

on the map "sp_a1_cube_fling_intro"
on the bridge to level 6 go too room, but slowly.
After entering the room, wait and hold movement until the door closes. Then return to the closed door. Will you take damage and have 5 fps

### Expected behavior

For it to not do this

### Screenshots

![report](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/72401974/2cfb068a-085f-43f1-9a29-747de4e04b17)
![report](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/72401974/1c5b93de-c4bc-4ff8-bb58-19e5796b2067)

### Desktop

OS: Windows 10 (64-bit) GPU name: NVIDIA GeForce GTX 1650 cpu name: Intel Core i5-4460 CPU: 8,13 3.20GHz

**Comment by StefanH-AT** [comment]
This will be fixed in 1.4.0
