### ISSUE TITLE
Crash on opening Portal Revolution

### ISSUE THREAD

**Issue by mike20737** [SecondFaceSoftware/PortalRevolution-Issues#199]
### Game Version

Version 1.1.0/Hotfix 2 for 1.0.6

### Describe the bug

After opening the game either by Steam or double clicking the desktop icon, an error box shows up saying "Process revolution.exe has just crashed" this only started to happen after hotfix 2 for 1.0.6. No matter how many times the game is re-launched, it will always crash with the feedback box.

### To Reproduce

1.Open Portal Revolution
2.Game crashes

### Expected behavior

The behavior expected is for the game to show the Strata logo and proceed to the main menu.

### Screenshots

![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/76716536/3a36778d-3516-47c8-9a22-dbedbed3ced7)

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/76716536/00c3a473-82ea-43b0-b018-689475d3d892

### Desktop

OS: Windows 10
GPU: Intel HD Graphics 6EU
CPU: Intel Core i5-3470 3.20GHz
RAM: 12GB DDR3

_yes my computer is that old_

**Comment by StefanH-AT** [comment]
Your intel integrated graphics won't run this game. Please check the system requirements
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/31664665/43c755de-df4d-48a9-be3f-07c729ede44a)
