### ISSUE TITLE
Conly disappears when plugging her in too quickly in sp_a3_labs

### ISSUE THREAD

**Issue by LeBrezzy** [SecondFaceSoftware/PortalRevolution-Issues#2]
When trying to instantly connect the module on the sp_a3_labs map, the module turns out to be out of place

1. Go to map "sp_a3_labs"
2. Instantly connect the module

The module should be in the receiver, in fact, it is located outside the map

[Video](https://www.youtube.com/watch?v=p7ug9XQNrL8)

 - OS: Windows 11
 - GPU name: RTX 3050 Ti Mobile
 - CPU name: Intel I5 11400H
 - RAM (Quantity + Spec): 2x8gb

**Comment by CatGirlGF** [comment]
Managed to recreate it by having my back facing the device and rotating camera. Maybe an issue based on distance to the device? 
[Video (streamable)](https://streamable.com/da7sv5)

- OS: W10
- GPU name: GTX 980
- CPU name: Ryzen 7 5800X3D
- RAM (Quantity + Spec): 32GB

**Comment by Mystical-Ace** [comment]
3 weeks later and this is FINALLY FIXED WOO!
