### ISSUE TITLE
Floor not accepting Portals in "The Climb"

### ISSUE THREAD

**Issue by Alatarvinyamar** [SecondFaceSoftware/PortalRevolution-Issues#204]
### Game Version

1.4

### Describe the bug

After the large "Not a real Test Chamber" in The Climb, you enter an office with a broken grate.  I can create a portal just outside but nothing in the room allows portals.  Walkthru on youtube shows that the floor should take a portal but it doesn't.

### To Reproduce

After the large "Not a real Test Chamber" in The Climb, you enter an office with a broken grate.  I can create a portal just outside but nothing in the room allows portals.  Walkthru on youtube shows that the floor should take a portal but it doesn't.

### Expected behavior

Floor need to accept portals

### Desktop

Windows 11, 3070, 32GB Ram

**Comment by Mystical-Ace** [comment]
Not a bug. You just need to orientate yourself correctly so that the portal can be placed down
