### ISSUE TITLE
Spelling mistake in French

### ISSUE THREAD

**Issue by MaledictYtb** [SecondFaceSoftware/PortalRevolution-Issues#209]
### Game Version

1.4.0

### Describe the bug

There is a spelling mistake in french. 

### To Reproduce

1. Switch the game to french
2. Go to the room after finishing the first 5 rooms
3. Here is the spelling mistake. 

### Expected behavior

The word 'quatité' doesn't exist. It's supposed to be "qualité"

### Screenshots

![20240225172030_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/94766634/71686305-0675-4aa3-b48c-f37370df4945)

### Desktop

OS : Fedora Kinoite
GPU name : RX 6700 XT

**Comment by StefanH-AT** [comment]
Apparently we already fixed this
