### ISSUE TITLE
Load/Death soft lock in final level

### ISSUE THREAD

**Issue by Ant1-Pr0phet** [SecondFaceSoftware/PortalRevolution-Issues#213]
### Game Version

1.4.0 (I think, its whatever the newest at the time is)

### Describe the bug

A soft lock that cannot be fixed by restarting, loading new save, dying, or portaling out. It is found in "The remote execution". The only way I know to get around this would be to restart the game but it's almost done so I don't want to do that.

### To Reproduce

In the second half of "the remote execution", if you run out of time while you press the button, the game kills you but sets your new save point 0.5 seconds before you die. 

### Expected behavior

The game would not soft lock me, it probably should have a "restart chapter" button in the "esc" menu.

### Screenshots

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/162846762/1da650c3-f178-484d-91e4-c29d8bd2d24c

### Desktop

Windows 11, Nivida rtx 1660 super, core i5 (idk the numbers, its sorta new), 16 gb ram,

**Comment by Mystical-Ace** [comment]
This should be fixed in the next version
