### ISSUE TITLE
Lasers don't inflict damage

### ISSUE THREAD

**Issue by TvSirTael** [SecondFaceSoftware/PortalRevolution-Issues#225]
### Game Version

Version 1.6.1

### Describe the bug

The laser doesn't damage the player

### To Reproduce

1. Find a laser in a test chamber
2. Walk into the laser

### Expected behavior

The Player doesn't take damage 

(I'm not sure if this is intentional or not. If it is, then I am sorry for posting this report)

### Screenshots

![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/167519512/2b3326bd-d483-4aa4-905f-b09fd73ce8eb)
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/167519512/b700ac40-8582-4527-82b7-b0768634c079)

### Desktop

OS: Windows 10
I don't know what else my computer has :/

**Comment by Wedge009** [comment]
I wondered if it might have been a deliberate design change...

**Comment by Mystical-Ace** [comment]
This is not a bug. We disabled laser collision due to it being annoying when walking through a portal with a laser, and overall not adding much to the gameplay.
