### ISSUE TITLE
Reflections repeating when moving camera

### ISSUE THREAD

**Issue by iidxgold** [SecondFaceSoftware/PortalRevolution-Issues#23]
**Describe the bug**
(Experienced in 5-1) When moving the camera, the water reflections stay, and will stack.
Weirdly enough, alt-tabbing and then re-entering the game will fix the reflections, but then the bug can be replicated again.

**To Reproduce**
[UNSURE IF THIS OCCURS GAME-WIDE. I EXPERIENCED THIS IN 5-1.]
Go to Chapter 5, select "Vacuum Tubes Introduction"
Enter chamber and complete first room with cube and vent as normal.
Enter second room.
Go on intended path until you drop off a small ledge into a puddle of water.
Look down and move camera around to see visual glitch.

**Expected behavior**
For this not to happen. 
**Screenshots**
![Screenshot (49)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/136996781/22dda34d-6db4-4576-817d-8a8801e4bb9c)
https://youtu.be/5bIZIy8a88U

**Desktop (please complete the following information):**
OS: Windows 10
GPU name: NVIDIA GeForce GPU
CPU name: Intel(R) Core(TM) i7-4765T CPU @ 2.00GHz 2.00 GHz
RAM (Quantity + Spec): 16GB

**Comment by ArcherTheReal** [comment]
Lmfao that's probably cause under the water there might not be any visible textures so you can see out of bounds and that just does that lol

**Comment by Mystical-Ace** [comment]
This appears to be an issue where if your Shader Detail setting is set to "Low" or "Medium"

**Comment by StefanH-AT** [comment]
Fixed
