### ISSUE TITLE
Plush Cube DLC 

### ISSUE THREAD

**Issue by DerWahreUnbekannte** [SecondFaceSoftware/PortalRevolution-Issues#234]
### Game Version

1.6.1

### Describe the bug

In the map sp_a1_bts_wind, the belt has normal cubes, not the plush variant. When you put one of them into the laser, the cube turns into a plush cube.

### To Reproduce

Go to the map
see, that the cubes on the belt are normal, not plush

### Expected behavior

I expected that the Cubes are Plush.

### Screenshots

![Screenshot 2024-08-15 160639](https://github.com/user-attachments/assets/414e50ec-f37a-499b-8410-b0576b38a21d)

![Screenshot 2024-08-15 163901](https://github.com/user-attachments/assets/510081f4-bcd8-4869-91f1-9720cdcd5f3f)

### Desktop

I think it was not important.

**Comment by StefanH-AT** [comment]
These cubes are a special type that explodes into gibs. I don't intend to make a special plush gibs but I think we can make the cube in the laser use the normal model for consistency
