### ISSUE TITLE
German Subtitle 

### ISSUE THREAD

**Issue by DerWahreUnbekannte** [SecondFaceSoftware/PortalRevolution-Issues#235]
### Game Version

1.6.1

### Describe the bug

One Voiceline isnt Translated in the Game.

### To Reproduce

Turn your Subtitles into German
Go to the last Elevator in the Map sp_a2_full_portalgun
See that the subtitle wasnt Translatet

### Expected behavior

The Voicline "This elevator will get us back on track, but it will take a while for us to get back to the surface." must translated to "Dieser Aufzug bringt uns zurück auf den Weg, aber es wird eine Weile dauern, bis wir zurück an der Oberfläche sind."

### Screenshots

![Screenshot 2024-08-15 164752](https://github.com/user-attachments/assets/05457811-d1aa-4400-9e2d-a33f3ddb9f66)
![Screenshot 2024-08-15 165802](https://github.com/user-attachments/assets/b3cb7f15-9811-4e31-92fe-f137b73b9ba5)

### Desktop

Its not important.

**Comment by StefanH-AT** [comment]
Good catch, fixed!
