### ISSUE TITLE
Alt-tabbing freezes game for a few seconds.

### ISSUE THREAD

**Issue by iidxgold** [SecondFaceSoftware/PortalRevolution-Issues#24]
**Describe the bug**
Alt-tabbing freezes game for a short while.

**To Reproduce**
Have game open, be in any menu/chamber
Hit Alt+Tab on your keyboard
Go to a different window
Alt+Tab again back to Revolution
Game will freeze for a few seconds, then all inputs made during freeze will happen. 

**Expected behavior**
Game should not freeze upon returning to the Portal: Revolution tab

**Screenshots**
https://youtu.be/xMjz3CdHRxM?si=HBbzqmHa95yzsO0J

**Desktop (please complete the following information):**
OS: Windows 10
GPU name: NVIDIA GeForce GPU
CPU name: Intel(R) Core(TM) i7-4765T CPU @ 2.00GHz 2.00 GHz
RAM (Quantity + Spec): 16GB

**Comment by JJL772** [comment]
Are you running in exclusive full screen mode or with borderless?

**Comment by iidxgold** [comment]
Fullscreen mode. The same one that the game boots you into on first launch.

**Comment by JJL772** [comment]
We'll look into this, thanks! In the meantime, you should use borderless.

**Comment by iidxgold** [comment]
Ok, thanks!
