### ISSUE TITLE
Can't shoot the orange hole.

### ISSUE THREAD

**Issue by crispersi** [SecondFaceSoftware/PortalRevolution-Issues#242]
### Game Version

1.3.0

### Describe the bug

Cannot shoot the orange portal with the right mouse. Tried to lay it on another key but no success.

### To Reproduce

press right mouse

### Expected behavior

red hole

### Screenshots

not available

### Desktop

Win11, Radeon RX 570 Series, i5-9600KF @ 3.7GHz, 16 GB RAM

**Comment by crispersi** [comment]
Solved, was too early in the game. sorry.

**Comment by crispersi** [comment]
Solved, was too early in the game. sorry.

**Comment by StefanH-AT** [comment]
glad your issue was resolved :)
