### ISSUE TITLE
Graphical Issue if i try to leave the application

### ISSUE THREAD

**Issue by ZiggyMcDude** [SecondFaceSoftware/PortalRevolution-Issues#26]
**Describe the bug**
When on Windowed Fullscreen or Fullscreen, try to exit the game with alt-tab, clicking windows etc. Will make the area where the windows have covered freak out and cover your screen with pixels of flashing colors, making it unable to play. (you can fix this by closing and reopening the game.) 

**To Reproduce**
1. Open Game
2. Try to leave game by alt + tab, clicking windows, etc.
3. See error

**Expected behavior**
Your screen should look like you have a broken gpu and freak out and display many rapidly changing colors.

**Screenshots**
![Screenshot 2024-01-07 100159](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/101502169/3bb44a2f-e996-415d-b5c9-910c0604bed2)
![Screenshot 2024-01-07 100220](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/101502169/04027981-e7b1-4405-bb73-984f138ec5a6)
![Screenshot 2024-01-07 100228](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/101502169/462043dc-d1f8-4c18-80dd-be690b6d74fd)
![Screenshot 2024-01-07 100235](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/101502169/cf409f51-85eb-4b6a-b7d9-3ede39136d08)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Version: 10.0.22621 Build 22621
 - GPU name: NVIDIA GeForce GTX 1650 (Laptop 4GB VRAM)
 - CPU name: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, 2100 Mhz, 4 Core(s), 8 Logical Processor(s)
 - RAM (Quantity + Spec): 32GB + 2400 MHZ

**Comment by StefanH-AT** [comment]
So all good then? 🤔

![image](https://github.com/user-attachments/assets/a5377b5b-226c-45e9-a407-b67bbccdc910)


In all seriousness I have never seen anything like this. Could you reproduce this? Source doesn't behave well when you tab in and out. From what I understand it's reloading _all_ materials and framebuffers from scratch, so I guess something went wrong and corrupted your frontbuffer. Please tell me if you find ways to reproduce this, otherwise there's nothing I can do

**Comment by ZiggyMcDude** [comment]
Hello, i'm unsure if it was a bug with the game or my laptop as a couple
weeks later my laptop died completely due to one of the ram slot being
destroyed or something. It's fixed now though so i can try reproduce it.
ill get back to you when i have time to try reproduce it. I got a new PC
after and played the game on there and it was amazing! thanks for the great
experience.

**Comment by ZiggyMcDude** [comment]
sorry for the long reply, i wasn't able to replicate the effect. Either an
update had fixed it or it was because of my laptop. thanks for the email!
