### ISSUE TITLE
Yellow flickering screen

### ISSUE THREAD

**Issue by idixtic** [SecondFaceSoftware/PortalRevolution-Issues#3]
**Describe the bug**
Somewhere during "The Climb", the map shown in the video "Fluid Flow in Pipes", i get some random yellow flickering glitch on my screen that I cant seem to reproduce.

**To Reproduce**
1. Go to the map I mentioned
2. After the part where you use the propulsion and repulsion gel to cross a gap to get onto a catwalk, flickering screen appears. Disappeared after I paused the game.

**Expected behavior**
No flickering screen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: gtx 1650 ti
 - CPU name: intel i5-10300h
 - RAM (Quantity + Spec): 2x16gb (32gb) 3200mhz

**Comment by idixtic** [comment]
It just happened again. It seems to happen whenever my velocity exceeds a certain amount.

**Comment by saismee** [comment]
this also happens when you are coated in gel

**Comment by idixtic** [comment]
yeah nevermind. its because i got coated in gel. i completely skipped over it because gel isnt yellow

**Comment by Starwort** [comment]
Yeah, the gel effect worked properly for me the first few times then started flickering instead of being solid. Not sure what's wrong with it

**Comment by Mystical-Ace** [comment]
This is due to a bug with the volumetrics. Latest update should have mitigated the issue. Alternatively, you can turn off the volumetrics in the settings to completely get rid of it
