### ISSUE TITLE
The player can't pick up the disk 

### ISSUE THREAD

**Issue by Minkerr** [SecondFaceSoftware/PortalRevolution-Issues#35]
**Describe the bug**
The player can't pick up the disk at the beginning of the map sp_a1_bts_wind_2 after load the save or restart the game

**To Reproduce**
1. In the first playthrough, I was able to take the disk and insert it into the computer (But nothing happened!)
2. Load a save or restart the game
3. Player can't pick up a disk

**Expected behavior**
I expected that if I inserted the disk into the computer, something would happen.

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/80471496/42db75e3-d67d-4b08-96ac-9c59fa4e7169)

**Desktop (please complete the following information):**
It is laptop:
 - OS: Windows 10
 - GPU name: Intel Core i5-9300H
 - CPU name: NVIDIA GeForce GTX 1650
 - RAM (Quantity + Spec): 16GB

**Comment by StefanH-AT** [comment]
Press Crtl to crouch

**Comment by Minkerr** [comment]
> Press Crtl to crouch

The disk is not available for interaction even if you come close to it with pressed Ctrl
