### ISSUE TITLE
Out of bounds on sp_a1_cube_fling_intro

### ISSUE THREAD

**Issue by MidniteTheProtogen** [SecondFaceSoftware/PortalRevolution-Issues#41]
**Describe the bug**
Out of bounds area on sp_a1_cube_fling_intro

**To Reproduce**
1. Do the fling
2. Jump to the newly revealed platform
3. Jump onto the pipe
4. Walk forwards into the out of bounds area

**Expected behavior**
Should be stopped by an invisible wall

**Video**
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/abd28e86-f1ce-4e44-b530-570fc3992258

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit 21H2
 - GPU name: NVIDIA GeForce GTX 1660 Ti
 - CPU name: AMD Ryzen 5 3600X
 - RAM (Quantity + Spec): 16GB (2x8gb) 1600MHz

**Comment by ArcherTheReal** [comment]
That isn't actually out of bounds I think

**Comment by MidniteTheProtogen** [comment]
> That isn't actually out of bounds I think

Considering that the props don't continue further and that there is nodraw in there. I highly doubt that it isn't out of bounds

**Comment by ArcherTheReal** [comment]
Out of bounds means that there is a direction from the player that isn't covered by a brush meaning that in that direction nothing is in front of the player,
In that example you are surrounded with a wall it just has a no draw texture it's still inbounds though
