### ISSUE TITLE
Out of bounds after "vent" area in sp_a1_bts_wind

### ISSUE THREAD

**Issue by MidniteTheProtogen** [SecondFaceSoftware/PortalRevolution-Issues#43]
**Describe the bug**
Out of bounds softlock after the "vent" area in sp_a1_bts_wind

**To Reproduce**
1. Bring a chair from earlier in the level to the spot in the screenshots
2. Use the chair to jump onto the railing
3. Jump off the railing into the pit

**Expected behavior**
Should be impossible to jump onto the railing

**Screenshots**
![20240107174021_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/c2fb588f-7fbb-4fd8-b1f5-0d6e7fe2d268)
![20240107174030_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/06730527-a145-4da0-95ba-e5902613c873)
![20240107174035_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/113823961/e1ee4c71-1a80-47ab-b1a5-7102f6c24321)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit 21H2
 - GPU name: NVIDIA GeForce GTX 1660 Ti
 - CPU name: AMD Ryzen 5 3600X
 - RAM (Quantity + Spec): 16GB (2x8gb) 1600MHz

**Comment by Sydnxt** [comment]
I already reported this issue under
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/issues/37
Mark as duplicate

**Comment by MidniteTheProtogen** [comment]
Duplicate of #37
