### ISSUE TITLE
Water gets dark when you look throught it from portals

### ISSUE THREAD

**Issue by weeToL** [SecondFaceSoftware/PortalRevolution-Issues#6]
**Describe the bug**
The toxic water gets dark when you look it throught a portal
**To Reproduce**
Open a portal facing to toxic water, and look throught there from another portal(i found it in chapter 14)
**Expected behavior**
Water needs to be brighter
**Screenshots**
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/137417792/cf78b239-973f-4bcf-92eb-6bbc74e5bcbe 
**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: RTX 3060
 - CPU name: i5 12400f
 - RAM (Quantity + Spec):
16GB(2x8GB)

**Comment by StefanH-AT** [comment]
Video doesn't work
