### ISSUE TITLE
The cube does not stop making a loud sound after the fling

### ISSUE THREAD

**Issue by BuT9l** [SecondFaceSoftware/PortalRevolution-Issues#60]
**Describe the bug**
As i know from portal 2, when you or qube flings, it make a specific sound. Here it wont stop do it after a fling ended. I think its linux problem

**To Reproduce**
1. Go to map sp_a1_cube_fling_intro
2. Pass 2 test chambers and reach cube fling introduction (as map name applies)
3. After qube flings, you can hear that sound

**Expected behavior**
Cube should stop do this sound after fling ends

**Bug reproduction**

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/102761689/8d921479-af27-406a-9459-2174b7e7f76b

**Desktop (please complete the following information):**
 - OS: Artix Linux x86_64
 - GPU name: NVIDIA GeForce RTX 4060 Max-Q / Mobile
 - CPU name: 12th Gen Intel(R) Core(TM) i5-12450H (12) @ 4,40 GHz
 - RAM (Quantity + Spec): 16GB

**Comment by StefanH-AT** [comment]
This is our dynamic music and not a bug
