### ISSUE TITLE
The image is blocked with incorrect level of level

### ISSUE THREAD

**Issue by faringdipi** [SecondFaceSoftware/PortalRevolution-Issues#62]
**Describe the bug**
The mistake is that if you pass through the wall without using portals, then the image is blurred on both sides. But if you repeat this using portals, then everything works. Everything is completely shown on the video. 

**To Reproduce**

1. Go to map sp_a1_catapult_intro
2. Fly to the second part of the field
3. Go to the red button
4. Make a jump around the corner and go through the wall

**Expected behavior**
It is enough just to remove this place that you can jump to

**Bug reproduction**

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/155977733/d3ec867d-9bb4-4b2d-af39-42534730c9bc

![bug](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/155977733/0be19568-2501-43d8-af76-47c31c52d76d)

**Desktop (please complete the following information):**

 - OS: Windows 10 Pro, x64
 - GPU name: NVIDIA GeForce GTX 1060 6 GB
 - CPU name: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz 3.50 GHz
 - RAM: 8GB

**Comment by ArcherTheReal** [comment]
I love red clipbrushes
