### ISSUE TITLE
Endless death autosave loop in finale

### ISSUE THREAD

**Issue by RoyBerardo** [SecondFaceSoftware/PortalRevolution-Issues#63]
**Describe the bug**
If you fling to the second (I believe) button in the finale, and press it as you land, it is perfectly timed so a turret will kill you the moment you press the button, sending you into an endless loop of dying and reloading.

**To Reproduce**
1. Go to the finale level, to the first button room with all the turrets, don't kill the turret in the back left corner, fling to the button and press it. The game will autosave and you will die repeatedly upon loading

**Expected behavior**
The game would avoid an autosave to prevent the player reloading into a fail state

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/32561682/b4325475-f1a7-4e9c-b1cb-4efacc66eab3)
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/32561682/0e741a26-4071-4f3f-b808-c7895a786f66)

**Desktop (please complete the following information):**
 - OS: windows
 - GPU name: rtx2070
 - CPU name: idk
 - RAM (Quantity + Spec): something like 40

**Comment by Mystical-Ace** [comment]
This should (finally) be fixed
