### ISSUE TITLE
Turrets are not visible and can not be picked up after loading a save

### ISSUE THREAD

**Issue by Unknown1144** [SecondFaceSoftware/PortalRevolution-Issues#66]
**Describe the bug**
Turrets appear invisible and can't be picked up after loading a save
**To Reproduce**
not sure how to reproduce

**Expected behavior**
The turrets to be visible and actually have the ability to pick up them

**Screenshots**
would send the video if the file size was under 10MB sorry!
![20240108190943_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/127354533/dd08e94e-53d0-42a0-89a3-67a164afa751)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: Nvidia GeForce RTX 3050
 - CPU name: AMD Ryzen 5 3600
 - RAM (Quantity + Spec): 16 GB 2667 MHz

**Comment by Montydog9** [comment]
does this bug happen consistently everytime you reload the save?

**Comment by Montydog9** [comment]
seems we have found the issue to this should be fixed now in the next update
