### ISSUE TITLE
snd_mute_losefocus should be a slider, not a toggle

### ISSUE THREAD

**Issue by vrad-exe** [SecondFaceSoftware/PortalRevolution-Issues#69]
**Describe the bug**
Arguably not a bug...`snd_mute_losefocus` in Strata can be set to a fractional value to partially lower the value of the audio when the window is out of focus. I verified that this feature is present and works in Revolution, but it isn't exposed in the UI. Setting it to a fractional value using the console causes the dropdown to become an arrow with no label.

**To Reproduce**
1. Go to the settings > audio tab
2. snd_mute_losefocus is a toggle instead of a slider

**Expected behavior**
It should be an "unfocused volume multiplier" slider

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/19228201/4fc45b3c-d659-4c70-91f2-a7018c7882cd)

**Comment by StefanH-AT** [comment]
Didn't know that was a scalar. Making it a slider
