### ISSUE TITLE
Void visible through hidden section

### ISSUE THREAD

**Issue by Ikethepro18** [SecondFaceSoftware/PortalRevolution-Issues#8]
**Describe the bug**
The void is quite clearly visible when looking through this hidden section on sp_a1_catapult_intro

**To Reproduce**
1. Open hidden section (I have zero clue how I did and I've been unable to reproduce it since
2. Look through the gap

**Expected behavior**
Well it shouldn't be the void

**Screenshots**
![20240106214703_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/73065710/b58bacef-007f-48c7-aea4-d8f7f13a6bf2)
![20240106214656_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/73065710/a66277ee-3bdb-4f3d-9f83-663fb5f8cd38)
![20240106214648_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/73065710/157b6667-9818-40c4-90dc-2774ce822273)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: NVIDIA GeForce GTX 1650
 - CPU name: 11th Gen Intel (R) Core (TM) i5-11400
 - RAM (Quantity + Spec): 16 GB DIMM @ 3600MHz

**Comment by ArcherTheReal** [comment]
That's not the "void" otherwise known as out of bounds its a red clip brush that has a similar buggy render effect
