### ISSUE TITLE
spontaneous rebound from the panel

### ISSUE THREAD

**Issue by Homewar** [SecondFaceSoftware/PortalRevolution-Issues#82]
**Describe the bug**

**To Reproduce**
1. Go to 'sp_a4_finale'
2. Reach the moment in the screenshot
3. fall onto the panel above

**Expected behavior**
falling on the panel without rebounding from it

**Screenshots**
[изображение](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/71277393/1ea69d66-3d2e-410c-ac85-1939320ed472)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit 22H2
 - GPU name: NVIDIA RTX3050 8gb
 - CPU name:  Intel Xeon CPU E5-2666 v3
 - RAM (Quantity + Spec): 32GB (4x8Gb) + 2666MHz

 video:https://drive.google.com/file/d/1VeB3FGF6yILiI7U8f5gTR1y-FWzVqbfH/view?usp=sharing

**Comment by ArcherTheReal** [comment]
The thing there is a scripted momentum trigger and it works by checking if you are within a certain velocity criteria and if so it applies a given velocity, intended behavior would be to make sure that when you do that thing you always go to the correct place, however it can be abused, I don't think this should be removed cause it would be quite useful for least portals speed runs

**Comment by Mystical-Ace** [comment]
I can't recreate this
