### ISSUE TITLE
Game freezes when looking through portals

### ISSUE THREAD

**Issue by d-k-bo-2** [SecondFaceSoftware/PortalRevolution-Issues#84]
**Describe the bug**
When I look through a portal, the game eventually freezes. The audio keeps playing. CPU and GPU usage drops to basically zero. When started from the terminal, there aren't any errors reported.

I managed to complete the chamber by always looking straight at the ground, but ran into the same issue in a later test chamber.

**To Reproduce**
1. Play Chapter 1, Chamber 1.
2. Click on the button.
3. Look through the blue portal.

**Expected behavior**
The game continues running normally.

**Screenshots**
[Portal Revolution freeze.webm](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/139637662/67e3ead9-abf7-4230-bd56-23de05d51654)

**Desktop (please complete the following information):**
 - OS: Fedora 39 (Linux 6.6.9, Mesa 23.3.2, GNOME 45.3) (both native and proton affected)
 - GPU name: AMD Radeon 760M (iGPU) 
 - CPU name: AMD Ryzen 5 7640U
 - RAM (Quantity + Spec): 1x 16 GB, 5600 MHz

**Comment by d-k-bo-2** [comment]
Some observations I made:

Setting `r_portal_stencil_depth 0` solves this issue, but since playing that way isn't really enjoyable I did try it only for a short time. Another user [reported on discord](https://discord.com/channels/269915658760749066/1193325811084824606/1196330962351571006) that they still encounter freezes every few minutes with that set.

I created a simple test chamber using Portal 2's chamber editor and loaded it successfully in Portal: Revolution. I could look, walk and fall through portals without any problems.

I tried playing on an older AMD based device using the same software stack and the issue didn't occur.

**Comment by lpuv** [comment]
Same exact issue here, same specs.

**Comment by d-k-bo-2** [comment]
I can now confirm that this must be an issue with either Mesa or the AMD drivers.

When using Proton with `PROTON_USE_WINED3D=1` set, which disables DXVK and enables WineD3D, the game doesn't freeze when using the default OpenGL renderer. After enabling the Vulkan backend for WineD3D using Protontricks, the game freezes again.

Unfortunately, the rendering quality is way worse when rendering to OpenGL.

**Comment by d-k-bo-2** [comment]
Mesa bug report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11031

**Comment by d-k-bo-2** [comment]
I no longer experience the issue.

For reference, I am now using Fedora Linux 40 with the Kernel 6.8.8-300.fc40.x86_64, Mesa 24.0.6 and Framework Laptop 13 Ryzen 7040 BIOS 3.05.
