### ISSUE TITLE
SP_a2_End - White walls not enterable.

### ISSUE THREAD

**Issue by Tuxek123** [SecondFaceSoftware/PortalRevolution-Issues#85]
In chapter 4: (SP_a2_End) once you reach the surface again and come to the big bridge to cross on the outside, a few of the only walls at which a portal can be placed cannot be walked through because the walls behind the elevator are clipped. I managed to get past it by placing the portal on the sign that reads "My new boss is a robot" but it was still pretty annoying and I almost thought I got stuck.

**To Reproduce**
1. Go to SP_a2_End
2. Place a portal on the walls near the elevator
3. Try to walk through and fail.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: RTX 3070
 - CPU name:  Rysen 5 5600X
 - RAM (Quantity + Spec): 16gb RAM

![20240110184951_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156232614/d2786bbe-e489-4462-8e74-86a49e115043)
![20240110185022_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/156232614/4857c5cd-39b7-4762-81ab-3c2a5db0e049)

**Comment by Mystical-Ace** [comment]
I can not recreate this, nor is there anything in Hammer that would suggest this being an issue.
