### ISSUE TITLE
Steam Cloud save doesn't work 

### ISSUE THREAD

**Issue by dotdlew** [SecondFaceSoftware/PortalRevolution-Issues#87]
**Describe the bug**
Game saves not syncing across devices despite Steam Cloud being a feature. 

**To Reproduce**
1. Save your game on Device 1
2. Exit game and confirm Steam Cloud is up to date
3. Start game on Device 2
4. Attempt to load game save, the list is empty or not update to date. 

**Expected behavior**
When saving the game Device 1, it's expected to see the game save on Device 2 when both Devices report Cloud Status Up to date.

**Device 1:**
 - OS: SteamOS Holo
 - GPU name: AMD Custom GPU 0405
 - CPU name: AMD Custom APU 0405
 - RAM (Quantity + Spec): 16GB

**Device 2:**
 - OS: Linux 6.6.9-200.fc39.x86_64
 - GPU name: GTX 1080
 - CPU name: AMD Ryzen 5 3600
 - RAM (Quantity + Spec): 32GB

**Comment by Jakdaw** [comment]
Seems it's just syncing config.cfg, not the actual SAVE directory.

**Comment by AllAboutEvelyn** [comment]
Same here, across 3 devices actual save files dont sync. Though progress does.
So i can chapter select to my progress point, just no saves.

**Comment by LeTabouret** [comment]
Had to reset my PC. I was at the last chapter. I wish I say this bug prior.

**Comment by plusran** [comment]
finished a chapter on my steam deck, came to PC for ultrawide play, and have to play though the whole chapter again.

**Comment by mdeguzis** [comment]
Please fix, it can't be insurmountable to just fix the files being saved (much like setting up rclone)

**Comment by vos6434** [comment]
Major update released today and this issue still isn't addressed, I really want to finish this game on my desktop rather than my steam deck.

**Comment by KLucky13** [comment]
same issue here!

**Comment by thanone2** [comment]
+1

**Comment by StefanH-AT** [comment]
Fixed

**Comment by TreyHam27** [comment]
Let's go it's fixed!!!!
