### ISSUE TITLE
Portalable surface glitch in sp_a2_paint_fizzler

### ISSUE THREAD

**Issue by CatzHoekk** [SecondFaceSoftware/PortalRevolution-Issues#88]
This is super minor since you don't even need portals to continue, just something i noticed.

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/69237200/2442fb04-5739-4e51-8d05-2c11a372de97

In words:

If you shoot at the right spot on the right portabable surface (next to the existing orange portal) the blue portal will appear one tile to the left. The portal gun particles also indicated that target. 

The jumps in the video are just because i had to edit it down to get below githubs 10MB file size limit.

**Comment by ArcherTheReal** [comment]
That's a nice portal bump lol

**Comment by ArcherTheReal** [comment]
Afaik it cannot be fixed without changing the actual model of the portal holder thing for orange

**Comment by Mystical-Ace** [comment]
What's wrong here?

Is that the blue portal ever so slightly clips underneath the autoportal emitter frame?

**Comment by CatzHoekk** [comment]
> What's wrong here?
> 
> Is that the blue portal ever so slightly clips underneath the autoportal emitter frame?

The portal completely jumps to the left of the orange portal even if i clearly shoot the portalable surface on the right. And it seems  to appear on the backside of whatever that surface is too.

**Comment by Mystical-Ace** [comment]
> > What's wrong here?
> > Is that the blue portal ever so slightly clips underneath the autoportal emitter frame?
> 
> The portal completely jumps to the left of the orange portal even if i clearly shoot the portalable surface on the right. And it seems to appear on the backside of whatever that surface is too.

That's just portal bumping, and the blue portal appearing behind the autoportal frame is a _really_ minor thing

**Comment by CatzHoekk** [comment]
Yeah absolutely a tiny thing. It's just that it feels very buggy since you don't even realize that there is a surface a portal could get bumped too. Just a small think taking away from the overly polish.
