### ISSUE TITLE
Can't pick up the disk on sp_a1_bts_wind_2.

### ISSUE THREAD

**Issue by MuckerMayhem** [SecondFaceSoftware/PortalRevolution-Issues#9]
**Describe the bug**
It isn't possible to grab the blue disk on sp_a1_bts_wind_2.

**To Reproduce**
1. Load sp_a1_bts_wind_2
2. Find the blue disk under the desk in the 'Test Chamber Observation' room.
3. Try to pick it up by pressing the 'Use' key on it from multiple angles.

**Expected behavior**
I _think_ the disk should grabable, there is a receptacle for it nearby. I asume we should be able to grab it and insert it in there.

**Screenshots**
![20240106141221_1](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/1161516/9b033bd9-5c22-41e1-ac3c-6fe7cd97758b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: GTX 2070 SUPER
 - CPU name: i7-12700K
 - RAM (Quantity + Spec): 16 GB

**Comment by benjaminpants** [comment]
Sometimes it can be picked up and sometimes it can't. When it is, it doesn't appear to do anything when inserted.

**Comment by StefanH-AT** [comment]
Press Crtl to crouch
