### ISSUE TITLE
Crosshair settings broken

### ISSUE THREAD

**Issue by pep0w** [SecondFaceSoftware/PortalRevolution-Issues#92]
Seems like the crosshair settings don't do anything. We only have one style or no crosshair at all with the "hidden" option... 
I was hoping to remove the 5 dots in the very middle and keep only the colored rings.

![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/7927176/fbe202a4-cebd-4582-aa8e-aef608f2d9bf)

Can you please do something about this. It's bothering me a lot.

**Comment by Mystical-Ace** [comment]
I don't believe it is possible to remove just the 5 dots. The settings effectively do what the console commands do. Hidden is just doing what it does in Portal 2. 

Probably won't be "fixed", sorry
