### ISSUE TITLE
Soft Lock on the Final Boss

### ISSUE THREAD

**Issue by Linuxydable** [SecondFaceSoftware/PortalRevolution-Issues#93]
**Describe the bug**
Infinite load screen due to a bad auto save timing.

**To Reproduce**
1. Start the final boss
2. Go to the 2nd phase of the boss
3. Press the button during the last second before timer run out.
4. Auto save was made at the moment you press the button and the game constantly load at the moment when the timer run out.

**Expected behavior**
Reseting the timer and continue the boss fight.

**Screenshots**
Better, I have a video :
https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/33342705/8719e981-3222-43be-9e89-9628e220909f

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro for Workstation (x64-bits)
 - GPU name: AMD Radeon RX 6900 XT
 - CPU name: AMD Ryzen 7 3800X
 - RAM (Quantity + Spec): 32Gb at 3200 Mhz

**Comment by MrWook** [comment]
Just got the same Issue. The bigger problem is that i have a autosave on entering the room with a button but if i try to load it, it will load the infinite loop autosave
