### ISSUE TITLE
Cannot Obtain Red Portal Gun

### ISSUE THREAD

**Issue by cheekywines** [SecondFaceSoftware/PortalRevolution-Issues#98]
Can't obtain the red portal gun, I approach the mannequin holding it and nothing happens. I did a wee little dance by jumping around it, even tried noclipping through it just in case, but nothing happens.

 - OS: Win11
 - GPU name: RTX 4070ti
 - CPU name: AMD Ryzen 7 5800X
 - RAM (Quantity + Spec): 32GB 3200MHz DDR4

**Comment by killermosi** [comment]
Press the use key while looking at the gun up close.
