### ISSUE TITLE
Save "corruption" upon pressing button during timer end 

### ISSUE THREAD

**Issue by me3127** [SecondFaceSoftware/PortalRevolution-Issues#99]
**bug description**
If you press (probably any) button just as the timer goes off, the game will autosave as the screen fades to white. Upon attempting to load said save, you will enter white fade fail state. 

secondary (probably) resultant bug: attempting to load a new game into chapter 8, loaded me into chapter 1, repeatedly. ended up having to no-clip all the way back through chapter 7 to get to 8. 

It is possible the second bug results from attempting to load a new game into an incomplete chapter. 

**To Reproduce**
1. Begin final countdown timer in ending sequence. 
2. wait until timer reaches either 0, or right before 0, unsure. 
3. hit a red button. (in my case, button number 3) 
4. attempt to load save. 

**Expected behavior**
I expected to load at the beginning of the room or upon pressing button 2. 

I also expected to be able to restart from the beginning of 8. 

**Screenshots**
deleted the save in order to no-clip back. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: [Sapphire PULSE Radeon RX 5700 XT 8 GB Video Card]
 - CPU name: [AMD Ryzen 5 3600X 3.8 GHz 6-Core Processor]
 - RAM (Quantity + Spec): [Corsair Vengeance LPX 16 GB (2 x 8 GB) DDR4-3000 CL15 Memory]

**Comment by Galifrey1965** [comment]
Same issue and unable to restart at level 8 as it just starts me from game beginning every time, even when selecting game start at level 8.
